version: '3.8'
services:
  gbuilder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gbuilder
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./home:/home/gbuilder/
      - ./home/pwsh/Start-LocalMod.ps1:/root/.config/powershell/profile.ps1
      - ./home/pwsh/Start-LocalMod.ps1:/root/.config/powershell/Microsoft.PowerShell_profile.ps1
    networks:
      - gidgebot
    depends_on:
      - builderdb
  builderdb:
    image: postgres:13-alpine
    container_name: builderdb
    volumes:
      - ./builderdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gidgebot
      POSTGRES_PASSWORD: gidgebot
      POSTGRES_DB: gidgebot
    networks:
      - gidgebot
    ports:
      - "5432:5432"
networks:
  gidgebot:
    external: true
